# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Mindever' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mindever

  # Firebase
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'FirebaseFirestoreSwift'

end
